SBERDOMA-102 fixed error with uuid
Create organization with `adminClient`:

```js
const admin = await makeLoggedInAdminClient()
await createTestOrganization(admin)
```

Following error occurs:

```stacktrace
console.log
    {
      message: 'select "t0".* from "public"."OrganizationEmployee" as "t0" left outer join "public"."OrganizationEmployee" as "t1" on "t0"."organization" = "t1"."id" where true and "t0"."organization" = $1 - operator does not exist: uuid = integer',
      locations: [ { line: 10, column: 5 } ],
      path: [ 'obj', 'employees' ],
      extensions: {
        code: 'INTERNAL_SERVER_ERROR',
        exception: {
          length: 200,
          name: 'error',
          severity: 'ERROR',
          code: '42883',
          hint: 'No operator matches the given name and argument types. You might need to add explicit type casts.',
          position: '139',
          file: 'parse_oper.c',
          line: '731',
          routine: 'op_error',
          stacktrace: [
            'error: select "t0".* from "public"."OrganizationEmployee" as "t0" left outer join "public"."OrganizationEmployee" as "t1" on "t0"."organization" = "t1"."id" where true and "t0"."organization" = $1 - operator does not exist: uuid = integer',
            '    at Parser.parseErrorMessage (/Users/antonal/Sites/sberdoma/condo/node_modules/pg-protocol/src/parser.ts:369:69)',
            '    at Parser.handlePacket (/Users/antonal/Sites/sberdoma/condo/node_modules/pg-protocol/src/parser.ts:188:21)',
            '    at Parser.parse (/Users/antonal/Sites/sberdoma/condo/node_modules/pg-protocol/src/parser.ts:103:30)',
            '    at Socket.<anonymous> (/Users/antonal/Sites/sberdoma/condo/node_modules/pg-protocol/src/index.ts:7:48)',
            '    at Socket.emit (events.js:315:20)',
            '    at Socket.EventEmitter.emit (domain.js:483:12)',
            '    at addChunk (_stream_readable.js:295:12)',
            '    at readableAddChunk (_stream_readable.js:271:9)',
            '    at Socket.Readable.push (_stream_readable.js:212:10)',
            '    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)',
            '    at TCP.callbackTrampoline (internal/async_hooks.js:120:14)'
          ]
        }
      },
      uid: 'ckolpq4xc0000bzt610d11ncr',
      name: 'GraphQLError'
    }

      at throwIfError (domains/common/utils/codegeneration/generate.test.utils.js:9:31)

Error: GraphQLError

    at throwIfError (/Users/antonal/Sites/sberdoma/condo/apps/condo/domains/common/utils/codegeneration/generate.test.utils.js:8:21)
    at Object.create (/Users/antonal/Sites/sberdoma/condo/apps/condo/domains/common/utils/codegeneration/generate.test.utils.js:54:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at createTestOrganization (/Users/antonal/Sites/sberdoma/condo/apps/condo/domains/organization/utils/testSchema/index.js:46:17)
    at Object.<anonymous> (/Users/antonal/Sites/sberdoma/condo/apps/condo/domains/organization/schema/Organization.test.js:43:9)
```

No errors when using `userClient`.

### Reason

A fragment `employees { id }` in `ORGANIZATION_FIELDS`, created by `createschema` util.

### Strange

There is analogous fragment `watchers { id name }` in `TICKET_FIELDS` and tests for User are passing.