DOMA-3099 custom progress tracking panel `TasksProgress` instead of Ant `notification`
When our React-component for tracking tasks will be mounted into Ant `notification`, following issues occurs:
1. When notification will be closed, a TaskProgressTracker React-component will be unmounted and therefore we cannot handle 'completed' status of a task to do some action
2. Ant notification is mounted outside of `MyApp` component, that has all necessary providers, so, by calling `useObject` front-end crashes with following error:
> Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry