fix(condo): DOMA-4798 error in changeClientSecret invoked from `refreshSbbolClientSecret`
Circular dependency caused a following error:
> TypeError: getSbbolSecretStorage is not a function at changeClientSecret (/app/apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js:13:32)

(cherry picked from commit af62b4f2ef85d2ea6bd1f18ec82ade65f34404f7)