fix(condo): DOMA-3800 try to fix tests of "export" module
Any next test case after case `[1, 0]` will be failed because of strange race condition
A `filename` variable seems to have a value of this case in next test case
This leads to following error:
> Error: ENOENT: no such file or directory, open '/var/folders/5g/1_1gv14n7y55cfw182lby3640000gn/T/8af5c380a4a8.csv'